### PR TITLE
Fix Bug in SourceValidator.php

### PR DESCRIPTION
**Pull request by acornforth**
encountered this bug while testing!

### CODE REVIEW

**Comment by Roshyo** [comment]
Hi. Could you please be more expensive about the error encountered ?

**Comment by acornforth** [comment]
I don't know why this failed the CI build exactly... don't have time today to investigate sorry, can take a look tomorrow if my schedule permits....

**Comment by acornforth** [comment]
> Hi. Could you please be more expensive about the error encountered ?

Yes, of course, the error was that the source validator didn't run at all. When attempting to save the redirect, I was hitting the Doctrine UniqueConstraintViolation exception at the Insert/Update query. the Validator should have picked this up before it got that far....

A quick look at the code and the bug should be obvious, comparing the 'source' field's value to the entire redirect entity is an obvious mistake, especially since there is no toString() method on that entity. I'm certain the author intended to compare the  'source' field, to the source property on the entity.

**Comment by Roshyo** [comment]
Indeed. Reproduced and your patch fixed it 👍

**Comment by loevgaard** [comment]
Hi @acornforth 

Thank you very much for fixing this. Can you make the tests pass?

**Comment by acornforth** [comment]
@loevgaard I would be happy to, but unlike my previous contributions, which i can kind of justify doing at my workplace since it's connected to what i'm working on, making the tests pass i will have to do on my own time, which i don't have much of at the moment... possibly next week i might be able to get to it :)

**Comment by loevgaard** [comment]
I hope you will get time doing it :)

**Comment by acornforth** [comment]
@loevgaard 
I have spent a couple of hours looking into fixing the tests, unfortunately i don't know enough about how phpspec works to be able to confidently do this... I have played around with a few things, but haven't managed to make the tests pass. Maybe yourself or another contributor could look into it?
really sorry

**Comment by Roshyo** [comment]
@acornforth I've creared a pull request inside your fork (Wow, such a "mise en abyme")

**Comment by loevgaard** [comment]
Thank you @acornforth and @Roshyo! 🍾

**Pull request merged**
