### PR TITLE
README improvements + official plugin review

### PR DESCRIPTION
**Pull request by Zales0123**
Hello @loevgaard, hello @Roshyo!

I've just taken a look at this plugin and it seems pretty nice, it also solves one of the issues on Sylius https://github.com/Sylius/Sylius/issues/9121. We would love to list it on [our official plugins list](https://sylius.com/plugins/), the only thing is a necessity of at least some basic functional/integration tests :) As a first approach they can be as easy as

```
Given I have a redirect configured from path "/old-path" to "/new-path"
When I try to access a "/old-path"
Then I should be redirected to a "/new-path"
```

They contain some kind of technical details, but a plugin is technical itself :) 

Please, let me know if you're willing to do it in the nearest future. And thanks for your amazing work! 🏅

### CODE REVIEW

**Comment by Roshyo** [comment]
Hi, since I've finally managed to have behat working on my environments, I might try to add some behat tests to cover this plugin. I might be able to do so next week. But if someone is willing to help on this, it would be appreciated.

**Comment by loevgaard** [comment]
Hi Mateusz

That would be great. @Roshyo are you up for the Behat test? :)

**Comment by Zales0123** [comment]
Hello guys! Have you tried to implement some tests for this (or one of the other plugins)? It would be great to have some of them on our official plugins list :)

**Comment by Roshyo** [comment]
Hi Zales,
As I've said to Loevgaard, I'm afraid I won't have time for those next weeks... The biggest part will be to get started with it, install bundles and configure them. If anybody can help on this, it would be very appreciated.

**Comment by loevgaard** [comment]
This is fixed by different commits and PR's. Thanks for making it official :D

**Pull request closed without merging**
